name: Continous Integration And Unit Tests

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checking Out Files
      uses: actions/checkout@v3
    
    - name: Setting Up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Application
      run: dotnet build -c Release --no-restore

    - name: Run Unit Tests
      run: dotnet test -c Release --no-build